ARG ODIN_REF=dev-2025-11

FROM alpine:3.20 AS build
# Need edge for LLVM/Clang 21
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories

RUN apk add --no-cache \
      git build-base clang21 llvm21-dev ca-certificates \
  && ln -s /usr/bin/llvm-config-21 /usr/bin/llvm-config || true

WORKDIR /src

# Shallow, single-branch clone for speed/cacheability
ARG ODIN_REF
RUN git clone --depth=1 --single-branch --branch "${ODIN_REF}" \
      https://github.com/odin-lang/Odin.git

WORKDIR /src/Odin

# Use BuildKit cache; parallelize the build
# (Enable BuildKit: DOCKER_BUILDKIT=1)
RUN --mount=type=cache,target=/root/.cache \
    make -j"$(nproc)" release-native

FROM alpine:3.20 AS runtime
# Need edge for llvm runtime libs if odin links against them
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
 && apk add --no-cache libstdc++ llvm21-libs ca-certificates clang21 python3

#tz data ommitted by default
RUN apk add --no-cache tzdata
#by default there local time isn't set since you have to install timezones
ENV TZ="America/Lima"

# Odin binary and libraries
#COPY --from=build /src/Odin/odin /usr/local/bin/odin
#COPY --from=build /src/Odin/core /usr/local/lib/odin/core
#COPY --from=build /src/Odin/vendor /usr/local/lib/odin/vendor
#COPY --from=build /src/Odin/base /usr/local/lib/odin/base
COPY --from=build . .

WORKDIR /src/Odin

ENV ODIN_ROOT=/src/Odin


##issues reported on github
#passed
#CMD ["./odin", "test", "tests/core", "-all-packages", \
#    "-define:ODIN_TEST_NAMES=test_core_math_big.test_big_math_vectors", \
#     "-define:ODIN_TEST_RANDOM_SEED=581997839029675"]

#failed
#CMD ["./odin", "test", "tests/core", "-all-packages", \
#     "-define:ODIN_TEST_NAMES=tests_core_posix.execute_struct_checks", \
#     "-define:ODIN_TEST_RANDOM_SEED=581997839029675"]

##Me looking for a complete list
#time issues are now resolved
#CMD ["./odin", "test", "tests/core", "-all-packages"]

#Final boss, POSIX
CMD ["./odin", "test", "tests/core", "-all-packages", \
     "-define:ODIN_TEST_NAMES=tests_core_posix.execute_struct_checks", \
     "-define:ODIN_TEST_RANDOM_SEED=581997839029675"]


